---

postgresql_locale: en_US.UTF-8

postgresql_pgdata: "/var/lib/pgsql/{{ postgresql_pgdg_ver_code }}/data"

postgresql_config: {}
# example:
#postgresql_config:
#  - shared_buffers: '256MB'

postgresql_config_defaults:
  log_directory: "/var/log/pgsql"
  log_filename: "postgresql-%Y%m%d_%H%M%S.log"
  log_file_mode: "0644"
  log_line_prefix: '%m [%p]: [%l] user=%u,db=%d '

postgresql_hba_entries: []

# References: https://github.com/geerlingguy/ansible-role-postgresql/blob/1.3.1/defaults/main.yml#L19
#postgresql_hba_entries:
#  - { type: host, database: foo, user: svc_foo, address: "192.168.0.0/24", auth_method: md5 }

postgresql_hba_entries_defaults:
  - type: local
    database: all
    user: "{{ postgresql_user }}"
    auth_method: peer

postgresql_pg_ident_entries: []
