---

- name: Ensure keycloak volume base directory exists
  file:
    path: /srv/keycloak
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Ensure keycloak data directory exists
  file:
    path: /srv/keycloak/data
    state: directory
    owner: root
    group: 1000
    mode: 0770

- name: Ensure keycloak log directory exists
  file:
    path: /srv/keycloak/log
    state: directory
    owner: root
    group: 1000
    mode: 0770

- name: Ensure keycloak truststore directory exists
  file:
    path: /srv/keycloak/truststore
    owner: root
    group: root
    mode: 0755
    state: directory


- name: Copy Dockerfile
  synchronize:
    src: docker/
    dest: /srv/keycloak/docker/
    owner: no
    group: no
    delete: yes
    archive: yes
    rsync_opts:
      - "--exclude='.*.sw[a-p]'"
  notify: Restart keycloak


- name: Pull keycloak base image
  docker_image:
    name: "jboss/keycloak:{{ keycloak_version }}"
    pull: yes

- name: Build custom keycloak image
  docker_image:
    path: /srv/keycloak/docker
    name: keycloak
    tag: latest
    buildargs:
      KEYCLOAK_VERSION: "{{ keycloak_version }}"
    state: present
    force: yes


- name: Configure service environment file
  copy:
    dest: /etc/sysconfig/keycloak
    content: |
      KEYCLOAK_PORT={{ keycloak_port }}

      POSTGRES_PORT_5432_TCP_ADDR={{ keycloak_db_hostname }}
      POSTGRES_ADDR={{ keycloak_db_hostname }}
      POSTGRES_PORT_5432_TCP_PORT=5432
      POSTGRES_PORT=5432
      POSTGRES_USER={{ keycloak_db_username }}
      POSTGRES_PASSWORD={{ keycloak_db_password }}
      POSTGRES_DB={{ keycloak_db_database }}
    owner: root
    group: root
    mode: 0600
  notify: Restart keycloak

- name: Install systemd service
  template:
    src: keycloak.service.j2
    dest: /etc/systemd/system/keycloak.service
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload systemd
    - Restart keycloak

- meta: flush_handlers

- name: Ensure keycloak service is started
  service:
    name: keycloak
    state: started
  notify: Wait for Keycloak to start up

- name: Enable keycloak service
  service:
    name: keycloak
    enabled: yes

- name: Install nginx vhost conf
  template:
    src: nginx/conf.d/keycloak.conf.j2
    dest: /etc/nginx/conf.d/keycloak.conf
    owner: root
    group: root
    mode: 0644
  notify: Reload nginx

- meta: flush_handlers

